//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        public int Id { get; set; }
        public Nullable<short> OrderDate { get; set; }
        public string Recipient { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string DeliverItem { get; set; }
        public string PaymentType { get; set; }
        public string Status { get; set; }
        public string Sumary { get; set; }
    }
}
